PROJECT=Stretto
PROJECT_NAME=Stretto
PROJECT_VERSION?=20130215215
PROJECT_EMAIL=jeffk@jdkoftinoff.com
PROJECT_LICENSE=ISC
PROJECT_MAINTAINER=jeffk@jdkoftinoff.com
PROJECT_COPYRIGHT=Copyright 2013
PROJECT_DESCRIPTION=
PROJECT_WEBSITE=https://stretto.statusbar.com/
PROJECT_IDENTIFIER=org.statusbar.stretto
TOP_LIB_DIRS+=.
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=
TEST_OUT_SUFFIX=txt

CONFIG_TOOLS=

